[2023-05-31 23:29:56,060] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.prepare_scopus_data scheduled__2023-04-14T00:00:00+00:00 [queued]>
[2023-05-31 23:29:56,069] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.prepare_scopus_data scheduled__2023-04-14T00:00:00+00:00 [queued]>
[2023-05-31 23:29:56,070] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-05-31 23:29:56,070] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-05-31 23:29:56,071] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-05-31 23:29:56,078] {taskinstance.py:1397} INFO - Executing <Task(PrepareScopusData): prepare_scopus_data> on 2023-04-14 00:00:00+00:00
[2023-05-31 23:29:56,083] {standard_task_runner.py:52} INFO - Started process 163 to run task
[2023-05-31 23:29:56,086] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'vic_investigacion_ETL', 'prepare_scopus_data', 'scheduled__2023-04-14T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/vic_investigacion_dag.py', '--cfg-path', '/tmp/tmpx540vv0r', '--error-file', '/tmp/tmp5bx68ru1']
[2023-05-31 23:29:56,088] {standard_task_runner.py:80} INFO - Job 10: Subtask prepare_scopus_data
[2023-05-31 23:29:56,145] {task_command.py:371} INFO - Running <TaskInstance: vic_investigacion_ETL.prepare_scopus_data scheduled__2023-04-14T00:00:00+00:00 [running]> on host 5d9ccb732815
[2023-05-31 23:29:56,192] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vic_investigacion_ETL
AIRFLOW_CTX_TASK_ID=prepare_scopus_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-14T00:00:00+00:00
[2023-05-31 23:29:56,194] {logging_mixin.py:115} INFO - Preparing Scopus Data
[2023-05-31 23:29:56,215] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/prepare_scopus_data_operator.py", line 21, in execute
    self.clean_authors_core_data()
  File "/opt/airflow/dags/prepare_scopus_data_operator.py", line 74, in clean_authors_core_data
    ],inplace=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 4913, in drop
    errors=errors,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['affiliation_current.affiliation.ip_doc.afnameid'\n 'affiliation_current.affiliation.ip_doc.manual_curation.@curated'\n 'affiliation_current.affiliation.ip_doc.manual_curation.curation_type'\n 'affiliation_current.affiliation.ip_doc.manual_curation.curation_source'] not found in axis"
[2023-05-31 23:29:56,227] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=vic_investigacion_ETL, task_id=prepare_scopus_data, execution_date=20230414T000000, start_date=20230531T232956, end_date=20230531T232956
[2023-05-31 23:29:56,234] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task prepare_scopus_data ("['affiliation_current.affiliation.ip_doc.afnameid'\n 'affiliation_current.affiliation.ip_doc.manual_curation.@curated'\n 'affiliation_current.affiliation.ip_doc.manual_curation.curation_type'\n 'affiliation_current.affiliation.ip_doc.manual_curation.curation_source'] not found in axis"; 163)
[2023-05-31 23:29:56,261] {local_task_job.py:156} INFO - Task exited with return code 1
