[2023-04-24 20:29:52,126] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.prepare_scopus_data manual__2023-04-24T20:29:27.815112+00:00 [queued]>
[2023-04-24 20:29:52,134] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.prepare_scopus_data manual__2023-04-24T20:29:27.815112+00:00 [queued]>
[2023-04-24 20:29:52,135] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-04-24 20:29:52,136] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-04-24 20:29:52,137] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-04-24 20:29:52,149] {taskinstance.py:1397} INFO - Executing <Task(PrepareScopusData): prepare_scopus_data> on 2023-04-24 20:29:27.815112+00:00
[2023-04-24 20:29:52,156] {standard_task_runner.py:52} INFO - Started process 12226 to run task
[2023-04-24 20:29:52,162] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'vic_investigacion_ETL', 'prepare_scopus_data', 'manual__2023-04-24T20:29:27.815112+00:00', '--job-id', '437', '--raw', '--subdir', 'DAGS_FOLDER/vic_investigacion_dag.py', '--cfg-path', '/tmp/tmpw3u7r_93', '--error-file', '/tmp/tmp_2ahc1_i']
[2023-04-24 20:29:52,165] {standard_task_runner.py:80} INFO - Job 437: Subtask prepare_scopus_data
[2023-04-24 20:29:52,248] {task_command.py:371} INFO - Running <TaskInstance: vic_investigacion_ETL.prepare_scopus_data manual__2023-04-24T20:29:27.815112+00:00 [running]> on host b136a0a45498
[2023-04-24 20:29:52,575] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vic_investigacion_ETL
AIRFLOW_CTX_TASK_ID=prepare_scopus_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-24T20:29:27.815112+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-24T20:29:27.815112+00:00
[2023-04-24 20:29:52,577] {logging_mixin.py:115} INFO - Preparing Scopus Data
[2023-04-24 20:29:52,615] {logging_mixin.py:115} INFO - Error --
[2023-04-24 20:29:52,618] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/prepare_scopus_data_operator.py", line 21, in execute
    self.clean_authors_core_data()
  File "/opt/airflow/dags/prepare_scopus_data_operator.py", line 85, in clean_authors_core_data
    currentAfilliton_dataframe = pd.concat([currentAfilliton_dataframe,affiliation_current])
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 307, in concat
    return op.get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 528, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3442, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
[2023-04-24 20:29:52,633] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=vic_investigacion_ETL, task_id=prepare_scopus_data, execution_date=20230424T202927, start_date=20230424T202952, end_date=20230424T202952
[2023-04-24 20:29:52,641] {standard_task_runner.py:97} ERROR - Failed to execute job 437 for task prepare_scopus_data (Reindexing only valid with uniquely valued Index objects; 12226)
[2023-04-24 20:29:52,672] {local_task_job.py:156} INFO - Task exited with return code 1
