[2023-07-04 21:56:01,994] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.profesores_validados manual__2023-07-04T21:56:00.863465+00:00 [queued]>
[2023-07-04 21:56:02,002] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.profesores_validados manual__2023-07-04T21:56:00.863465+00:00 [queued]>
[2023-07-04 21:56:02,003] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-04 21:56:02,003] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-04 21:56:02,004] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-04 21:56:02,012] {taskinstance.py:1397} INFO - Executing <Task(PrepareProfesoresValidados): profesores_validados> on 2023-07-04 21:56:00.863465+00:00
[2023-07-04 21:56:02,019] {standard_task_runner.py:52} INFO - Started process 3027 to run task
[2023-07-04 21:56:02,023] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'vic_investigacion_ETL', 'profesores_validados', 'manual__2023-07-04T21:56:00.863465+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/vic_investigacion_dag.py', '--cfg-path', '/tmp/tmpmzyh8m8m', '--error-file', '/tmp/tmpunib508b']
[2023-07-04 21:56:02,025] {standard_task_runner.py:80} INFO - Job 13: Subtask profesores_validados
[2023-07-04 21:56:02,093] {task_command.py:371} INFO - Running <TaskInstance: vic_investigacion_ETL.profesores_validados manual__2023-07-04T21:56:00.863465+00:00 [running]> on host f4f0af373b5a
[2023-07-04 21:56:02,155] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vic_investigacion_ETL
AIRFLOW_CTX_TASK_ID=profesores_validados
AIRFLOW_CTX_EXECUTION_DATE=2023-07-04T21:56:00.863465+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-04T21:56:00.863465+00:00
[2023-07-04 21:56:02,157] {logging_mixin.py:115} INFO - Preparing Profesores validados
[2023-07-04 21:56:02,573] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/prepare_profesores_validado.py", line 25, in execute
    self.cleanData()
  File "/opt/airflow/dags/prepare_profesores_validado.py", line 35, in cleanData
    profesores.drop(columns=["SCOPUS_AUTHOR_ID"],inplace=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 4913, in drop
    errors=errors,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['SCOPUS_AUTHOR_ID'] not found in axis"
[2023-07-04 21:56:02,589] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=vic_investigacion_ETL, task_id=profesores_validados, execution_date=20230704T215600, start_date=20230704T215601, end_date=20230704T215602
[2023-07-04 21:56:02,597] {standard_task_runner.py:97} ERROR - Failed to execute job 13 for task profesores_validados ("['SCOPUS_AUTHOR_ID'] not found in axis"; 3027)
[2023-07-04 21:56:02,656] {local_task_job.py:156} INFO - Task exited with return code 1
